const ADD_LIST_PENDING = "LIST_ADD_PENDING";
const ADD_LIST_SUCCESS = "LIST_ADD_SUCCESS";
const ADD_LIST_FAILED = "LIST_ADD_FAILED";

const EDIT_LIST_PENDING = "EDIT_LIST_PENDING";
const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
const EDIT_LIST_FAILED = "EDIT_LIST_FAILED";

const DELETE_LIST_PENDING = "DELETE_LIST_PENDING";
const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
const DELETE_LIST_FAILED = "DELETE_LIST_FAILED";

const LOAD_TABLE_LEXEMES = "LOAD_TABLE_LEXEMES";

module.exports = {
  ADD_LIST_PENDING,
  ADD_LIST_SUCCESS,
  ADD_LIST_FAILED,

  EDIT_LIST_PENDING,
  EDIT_LIST_SUCCESS,
  EDIT_LIST_FAILED,

  DELETE_LIST_PENDING,
  DELETE_LIST_SUCCESS,
  DELETE_LIST_FAILED,

  LOAD_TABLE_LEXEMES,
};
