const LOAD_LIST_PENDING = "LOAD_LIST_PENDING";
const LOAD_LIST_SUCCESS = "LOAD_LIST_SUCCESS";
const LOAD_LIST_FAILED = "LOAD_LIST_FAILED";

const ADD_LIST_PENDING = "LIST_ADD_PENDING";
const ADD_LIST_SUCCESS = "LIST_ADD_SUCCESS";
const ADD_LIST_FAILED = "LIST_ADD_FAILED";
const INIT_ADD_LIST = "INIT_ADD_LIST";

const EDIT_LIST_PENDING = "EDIT_LIST_PENDING";
const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
const EDIT_LIST_FAILED = "EDIT_LIST_FAILED";
const INIT_EDIT_LIST = "INIT_EDIT_LIST";

const DELETE_LIST_PENDING = "DELETE_LIST_PENDING";
const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
const DELETE_LIST_FAILED = "DELETE_LIST_FAILED";

const LOAD_TABLE_LEXEMES = "LOAD_TABLE_LEXEMES";

const UPDATE_TABLE_INPUT_VALUE = "UPDATE_TABLE_INPUT_VALUE";
const UPDATE_LIST_INPUT_VALUE = "UPDATE_LIST_INPUT_VALUE";
const UPDATE_MODAL_INPUT_VALUE = "UPDATE_MODAL_INPUT_VALUE";
const ADD_EMPTY_LEXEME = "ADD_EMPTY_LEXEME";

const TOGGLE_TABLE_EDIT = "TOGGLE_TABLE_EDIT";

const ADD_LEXEMES_PENDING = "ADD_LEXEMES_PENDING";
const ADD_LEXEMES_SUCCESS = "ADD_LEXEMES_SUCCESS";
const ADD_LEXEMES_FAILED = "ADD_LEXEMES_FAILED";

const EDIT_LEXEMES_PENDING = "EDIT_LEXEMES_PENDING";
const EDIT_LEXEMES_SUCCESS = "EDIT_LEXEMES_SUCCESS";
const EDIT_LEXEMES_FAILED = "EDIT_LEXEMES_FAILED";

const DELETE_LEXEMES_PENDING = "DELETE_LEXEMES_PENDING";
const DELETE_LEXEMES_SUCCESS = "DELETE_LEXEMES_SUCCESS";
const DELETE_LEXEMES_FAILED = "DELETE_LEXEMES_FAILED";

module.exports = {
  LOAD_LIST_PENDING,
  LOAD_LIST_SUCCESS,
  LOAD_LIST_FAILED,

  ADD_LIST_PENDING,
  ADD_LIST_SUCCESS,
  ADD_LIST_FAILED,
  INIT_ADD_LIST,

  EDIT_LIST_PENDING,
  EDIT_LIST_SUCCESS,
  EDIT_LIST_FAILED,
  INIT_EDIT_LIST,

  DELETE_LIST_PENDING,
  DELETE_LIST_SUCCESS,
  DELETE_LIST_FAILED,

  LOAD_TABLE_LEXEMES,

  UPDATE_TABLE_INPUT_VALUE,
  UPDATE_MODAL_INPUT_VALUE,
  UPDATE_LIST_INPUT_VALUE,
  ADD_EMPTY_LEXEME,

  TOGGLE_TABLE_EDIT,

  ADD_LEXEMES_PENDING,
  ADD_LEXEMES_SUCCESS,
  ADD_LEXEMES_FAILED,

  EDIT_LEXEMES_PENDING,
  EDIT_LEXEMES_SUCCESS,
  EDIT_LEXEMES_FAILED,

  DELETE_LEXEMES_PENDING,
  DELETE_LEXEMES_SUCCESS,
  DELETE_LEXEMES_FAILED,
};
