const MENU = {
  PROFILE: "MENU_PROFILE",
  LISTS: "MENU_LISTS",
  LEXEMES: "MENU_LEXEMES",
  MATCHING: "MENU_MATCHING",
  WRITING: "MENU_WRITING",
  SETTINGS: "MENU_SETTINGS",
};

module.exports = {
  MENU,
};
